name: toastr
version: 0.1.0+1
description: Port of toastr to Dart.
author: Kevin Visscher <kevin@clickseeker.nl>
homepage: https://github.com/kvisscher/toastr
dependencies:
  test: ">=0.12.15 <0.13.0"
